# Generated by Django 4.2.6 on 2023-12-15 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField(default='')),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('No Aplica', 'Prefiero no decirlo')], max_length=20)),
                ('nacionalidad', models.CharField(choices=[('Estadounidense', 'Estadounidense'), ('Británico', 'Británico'), ('Canadiense', 'Canadiense'), ('Chileno', 'Chileno'), ('Peruano', 'Peruano'), ('Otro', 'Otro')], max_length=50)),
                ('premios', models.PositiveIntegerField(default='')),
                ('anio_debut', models.PositiveIntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.PositiveIntegerField(default='')),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('No Aplica', 'Prefiero no decirlo')], max_length=20)),
                ('nacionalidad', models.CharField(choices=[('Estadounidense', 'Estadounidense'), ('Británico', 'Británico'), ('Canadiense', 'Canadiense'), ('Chileno', 'Chileno'), ('Peruano', 'Peruano'), ('Otro', 'Otro')], max_length=50)),
                ('premios', models.PositiveIntegerField(default='')),
                ('cantidad_peliculas', models.PositiveIntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('minutos_duracion', models.PositiveIntegerField(default=0)),
                ('genero', models.CharField(choices=[('Accion', 'Accion'), ('Comedia', 'Comedia'), ('Drama', 'Drama'), ('Terror', 'Terror'), ('Otros', 'Otros')], max_length=10)),
                ('fecha_de_estreno', models.CharField(default='dd/mm/aaaa', max_length=10)),
                ('presupuesto', models.PositiveIntegerField(default=0)),
                ('recaudacion', models.PositiveIntegerField(default=0)),
                ('actor_protagonista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdministradorDePeliculas.actor')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdministradorDePeliculas.director')),
            ],
        ),
    ]
